[fancy_source_query]
# 默认超时等待 5s
timeout = 5
# 默认查询池缓存 20s
cache_delay = 20
# 默认限制文本输出 5 行，超过 5 行的转成图片输出
output_max_lines = 5
# 一次性随机抽取三方图的最大数量
map_choices_max_counts = 15
# Fancy Source Query 可以配置地图数据库，方便将地图代码转换成人类可读的地图名
# 该路径相对于 nonebot 进程工作目录
mapnames_db = "mapnames.toml"
# 默认的服务器组，在不传入组名时使用此组
default_server_group = "A"
# 转图片时的字号，px
fontsize = 16

[fancy_source_query.impaper]
# 建议留空，加载默认的更纱黑体，
# 或者指定一个 ttf 文件的路径。
# font.path =
[fancy_source_query.impaper.layout]
# 外边距，按上右下左的顺序（和 CSS 里的习惯一致），px
# 右边距建议拉大一点，防止手机上看时像素被遮住
margin = [6, 6, 18, 6]
# 内边距，按上右下左的顺序（和 CSS 里的习惯一致），px
padding = [2, 2, 2, 2]
# 行间距，px
spacing = 2
[fancy_source_query.impaper.typesetting]
# 行宽，英文1，汉字2
line_width = 52
# 折行缩进
indentation = "  "

# 格式化查询数据的模板
[fancy_source_query.fmt]
server_info = "服务器：{name}\n概况：({players:>2d}/{max_players:>2d})[{mapname}]"
player_info = "[{score}]({minutes:.1f}min){name}"
rule_info = "({key} = {value})"
players_count = "总人数：{players}"
query_time = "查询时间：{time}"
# strftime 格式符
time = "%Y-%m-%d %H:%M:%S"

# Fancy Source Query 可以为不同的 QQ 群设置不同的服务器组
# 为不同的群分别提供查询服务，例如为 A 群配置服务器组 AG, 其中包含服务器 A1, A2, A3；
# 为 B 群配置服务器组 BG，其中包含服务器 B1, B2, B3；
# 为 开发者测试群 配置服务器组 DEVG，其中包含所有服务器；
# 那么机器人在 A 群中查询时只会考虑 A1, A2, A3 服务器，以此类推。
[[fancy_source_query.server_groups]]
name = "A"
related_sessions = ["<QQ群号A>", "<开发者测试群>"]
[[fancy_source_query.server_groups]]
name = "B"
related_sessions = ["<QQ群号B>", "<开发者测试群>"]

[[fancy_source_query.servers]]
# 此处的 A 需要与 server_group.name 相同
group = "A"
name = "A1"
host = "127.0.0.1"
port = 65501
[[fancy_source_query.servers]]
group = "A"
name = "A2"
host = "127.0.0.1"
port = 65502
[[fancy_source_query.servers]]
group = "B"
name = "B1"
host = "127.0.0.1"
port = 64501
